### Dataset ###
data:
  name: synthetic_pretrain
  folder: ./datasets/synthetic/pretrain

### Pretrain ###
train:
  epochs: 200
  batch_size: 256
  lr: 1.0e-3
  model_path: ""
  output_folder: pretrain
  val_epoch_interval: 10
  display_interval: 10
  ctrl_attrs: [[trend_types], [trend_directions], [season_cycles], [trend_types, trend_directions], [trend_types, season_cycles], [trend_directions, season_cycles]]
